### ISSUE TITLE
deletes everything in the directory

### ISSUE THREAD

**Issue by alibama** [devgiants/mbox-splitter#1]
so i ran this and it did two things - 

first it deleted every file in the directory i was in (itself, the mbox file, etc... everything)

then it printed this Warning: fopen(/mbox-splitter-master/lgalist.mbox): failed to open stream: No such file or directory in /mbox-splitter-master/mbox_splitter.php on line 31

i'm guessing this isn't the desired result, and may have something to do with something on my end.... i tested it on two separate machines, an ubuntu 14.04 lts box with php installed via apt-get and then my mac with php installed via macports

**Comment by mcsitter** [comment]
This is a long time ago but in the script after checking that args are input it unlinks all the files in the destination folder. THIS IS REALLY UNEXPECTED and i assume is what caused #3 to be opened as well. I would recommend just deleting the lines which delete the files or at least *warn* in the README. I appreciate this script otherwise, but in the current state this respository is dangerous.

If you want i can make a PR and either change the script, adding a warning inside or a confirmation or as i would prefer just delete the lines, which clear the folder. Or i can add a WARNING to the README. This repo ranks highly in google results and i want to help people out who will experience potential trouble in the future.

**Comment by devgiants** [comment]
Hello,

Sorry for the very late reply. As you well aware of, I did not maintain this repo after my initial personal use.

Feel free to PR in the best way you consider. In the meanwhile I will start a complete rewrite using components and options in CLI call in order to handle those cases.
